version: '3'
services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000  # Set the backend API URL for the frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile  # Specify the Dockerfile to use
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=my_demo_database
      - DATABASE_URL=postgres://username:pgpassword@db/my_demo_database
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_demo_database
      DATABASE_URL: postgres://username:pgpassword@db/my_demo_database
    volumes:
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
